name: Build and Test

env:
  JAVA_VERSION: '11'                  # set this to the Java version to use
  DISTRIBUTION: temurin               # set this to the Java distribution
  ARCHITECTURE: x64

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*
jobs:
  build_and_test:
    name: Java Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          architecture: ${{ env.ARCHITECTURE }}
      - name: Run Maven
        env:
          AMP_ARTIFACTS_PAT: ${{ secrets.AMP_ARTIFACTS_PAT }}
          AMP_ARTIFACTS_PAT_BASE64: ${{ secrets.AMP_ARTIFACTS_PAT_BASE64 }}
        run: mvn test -s settings.xml