name: Deploy Artifacts
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Deploy Artifacts to Azure
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          architecture: x64
          distribution: temurin
      - name: Maven Deploy
        env:
          AMP_ARTIFACTS_PAT: ${{ secrets.AMP_ARTIFACTS_PAT }}
          AMP_ARTIFACTS_PAT_BASE64: ${{ secrets.AMP_ARTIFACTS_PAT_BASE64 }}
        run: mvn deploy -s settings.xml