name: Deploy Container
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Deploy Artifacts to GH Packages
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64
      - name: Mvn CLI 
        run: |
          mvn dependency:get -DgroupId=com.aftia.adobe -DartifactId=doc-cloud-services.core -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dclassifier=jar-with-dependencies -DremoteRepositories=aftia-github::::https://maven.pkg.github.com/AFTIA/com.aftia.adobe.doc-cloud-services -Ddest=./
          mvn install:install-file -Dfile=./doc-cloud-services.core-1.0-SNAPSHOT-jar-with-dependencies.jar -DgroupId=com.aftia.adobe -DartifactId=doc-cloud-services.core -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dclassifier=jar-with-dependencies
      - name: Run Maven
        run: mvn --settings settings.xml clean deploy
        env:
          PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}